services:
  scan-serie-machine:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    env_file:
      - .env

    environment:
      HOST: 0.0.0.0
      PORT: 5005

    ports:
      - "5005:5005"
